"""Diagnostic rules."""

from trainmedic.rules.gradient_rules import (
    GLOBAL_GRADIENT_NORM_BELOW_THRESHOLD,
    GLOBAL_GRADIENT_NORM_EXCEEDS_THRESHOLD,
    GRADIENT_CONTAINS_INF,
    GRADIENT_CONTAINS_NAN,
    NO_PARAMETERS_SELECTED_FOR_GRADIENT_MONITORING,
    PARAMETER_GRADIENT_IS_NONE,
)
from trainmedic.rules.numerical_rules import (
    FORWARD_OUTPUT_CONTAINS_INF,
    FORWARD_OUTPUT_CONTAINS_NAN,
)
from trainmedic.rules.optimizer_rules import inspect_optimizer

__all__ = [
    "FORWARD_OUTPUT_CONTAINS_INF",
    "FORWARD_OUTPUT_CONTAINS_NAN",
    "GLOBAL_GRADIENT_NORM_BELOW_THRESHOLD",
    "GLOBAL_GRADIENT_NORM_EXCEEDS_THRESHOLD",
    "GRADIENT_CONTAINS_INF",
    "GRADIENT_CONTAINS_NAN",
    "NO_PARAMETERS_SELECTED_FOR_GRADIENT_MONITORING",
    "PARAMETER_GRADIENT_IS_NONE",
    "inspect_optimizer",
]
