"""Diagnostic rules."""

from trainmedic.rules.gradient_rules import (
    GLOBAL_GRADIENT_NORM_BELOW_THRESHOLD,
    GLOBAL_GRADIENT_NORM_EXCEEDS_THRESHOLD,
    GRADIENT_CONTAINS_INF,
    GRADIENT_CONTAINS_NAN,
    NO_PARAMETERS_SELECTED_FOR_GRADIENT_MONITORING,
    PARAMETER_GRADIENT_IS_NONE,
)
from trainmedic.rules.mode_rules import (
    BATCHNORM_MODE_MISMATCH,
    CALLED_SUBMODULE_MODE_MISMATCH,
    DROPOUT_MODE_MISMATCH,
    FORWARD_NOT_OBSERVED_DURING_MODE_MONITORING,
    GRADIENT_TRACKING_DISABLED_DURING_TRAINING,
    GRADIENT_TRACKING_ENABLED_DURING_EVALUATION,
    MODEL_IN_EVAL_DURING_TRAINING,
    MODEL_IN_TRAIN_DURING_EVALUATION,
)
from trainmedic.rules.numerical_rules import (
    FORWARD_OUTPUT_CONTAINS_INF,
    FORWARD_OUTPUT_CONTAINS_NAN,
)
from trainmedic.rules.optimizer_rules import inspect_optimizer
from trainmedic.rules.update_rules import (
    NO_PARAMETERS_SELECTED_FOR_UPDATE_MONITORING,
    OPTIMIZER_STEP_DID_NOT_COMPLETE,
    OPTIMIZER_STEP_NOT_OBSERVED,
    PARAMETER_UPDATE_NOT_DETECTED,
    UPDATE_CHECK_SKIPPED_FOR_UNKNOWN_LEARNING_RATE,
    ZERO_LEARNING_RATE_FOR_UPDATE_CANDIDATES,
)

__all__ = [
    "FORWARD_OUTPUT_CONTAINS_INF",
    "FORWARD_OUTPUT_CONTAINS_NAN",
    "FORWARD_NOT_OBSERVED_DURING_MODE_MONITORING",
    "GLOBAL_GRADIENT_NORM_BELOW_THRESHOLD",
    "GLOBAL_GRADIENT_NORM_EXCEEDS_THRESHOLD",
    "GRADIENT_CONTAINS_INF",
    "GRADIENT_CONTAINS_NAN",
    "GRADIENT_TRACKING_DISABLED_DURING_TRAINING",
    "GRADIENT_TRACKING_ENABLED_DURING_EVALUATION",
    "BATCHNORM_MODE_MISMATCH",
    "CALLED_SUBMODULE_MODE_MISMATCH",
    "DROPOUT_MODE_MISMATCH",
    "MODEL_IN_EVAL_DURING_TRAINING",
    "MODEL_IN_TRAIN_DURING_EVALUATION",
    "NO_PARAMETERS_SELECTED_FOR_GRADIENT_MONITORING",
    "NO_PARAMETERS_SELECTED_FOR_UPDATE_MONITORING",
    "OPTIMIZER_STEP_DID_NOT_COMPLETE",
    "OPTIMIZER_STEP_NOT_OBSERVED",
    "PARAMETER_GRADIENT_IS_NONE",
    "PARAMETER_UPDATE_NOT_DETECTED",
    "UPDATE_CHECK_SKIPPED_FOR_UNKNOWN_LEARNING_RATE",
    "ZERO_LEARNING_RATE_FOR_UPDATE_CANDIDATES",
    "inspect_optimizer",
]
